baseURL = "http://example.org/"
languageCode = "zh"
title = "My New Hugo Site"
theme = "docsy"



# Mounts
[module]
  [[module.mounts]]
    source = "content"
    target = "content"
    lang = "en"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Algolia
algolia_docsearch = true
offlineSearch = false


[params.ui]
sidebar_menu_compact = false
navbar_logo = true
sidebar_search_disable = true
